const http2 = require('http2');

const DUPLICATION_ERROR_11000 = 11000;

const {
  HTTP_STATUS_OK: OK_200,
  HTTP_STATUS_CREATED: CREATED_201,
  HTTP_STATUS_BAD_REQUEST: BAD_REQUEST_400,
  HTTP_STATUS_UNAUTHORIZED: UNAUTHORIZED_401,
  HTTP_STATUS_FORBIDDEN: FORBIDDEN_403,
  HTTP_STATUS_NOT_FOUND: NOT_FOUND_404,
  HTTP_STATUS_CONFLICT: CONFLICT_409,
  HTTP_STATUS_INTERNAL_SERVER_ERROR: INTERNAL_SERVER_ERROR_500,
} = http2.constants;

const RECURRING_EMAIL_MESSAGE = 'Такой email уже зарегистрирован.';
const INCORRECT_USER_ID_MESSAGE = 'Пользователь с таким ID не найден.';
const INCORRECT_MOVIE_ID_MESSAGE = 'Фильм с таким ID не найден.';
const DELETE_ALIEN_MOVIE = 'Попытка удаления НЕ вашего фильма.';
const DELETE_MOVIE_SUCCESSFULLY = 'Фильм удален.';
const UNAUTHORIZED_MESSAGE = 'Необходима авторизация!';
const NOT_FOUND_MESSAGE = 'Страница не найдена.';
const SERVER_CRASH_MESSAGE = 'Внимание! Сервер сейчас упадет!';
const INVALID_EMAIL_OR_PASS_MESSAGE = 'Неправильные почта или пароль.';

module.exports = {
  OK_200,
  CREATED_201,
  BAD_REQUEST_400,
  UNAUTHORIZED_401,
  FORBIDDEN_403,
  NOT_FOUND_404,
  CONFLICT_409,
  INTERNAL_SERVER_ERROR_500,
  DUPLICATION_ERROR_11000,
  RECURRING_EMAIL_MESSAGE,
  INCORRECT_USER_ID_MESSAGE,
  INCORRECT_MOVIE_ID_MESSAGE,
  DELETE_ALIEN_MOVIE,
  DELETE_MOVIE_SUCCESSFULLY,
  UNAUTHORIZED_MESSAGE,
  NOT_FOUND_MESSAGE,
  SERVER_CRASH_MESSAGE,
  INVALID_EMAIL_OR_PASS_MESSAGE,
};
